//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreweryServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string Admin_EmployeeID { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_FirstName { get; set; }
        public string Admin_Lastname { get; set; }
        public string Admin_IdentityNumber { get; set; }
        public string Admin_JobRole { get; set; }
        public Nullable<System.DateTime> Admin_Dob { get; set; }
        public string Admin_CellNumber { get; set; }
        public string Admin_Address { get; set; }
        public Nullable<System.DateTime> Admin_DateJoined { get; set; }
    }
}
