//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreweryServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public string EmployeeID { get; set; }
        public string Vehicle_ID { get; set; }
        public string Employee_FirstName { get; set; }
        public string Employee_LastName { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<System.TimeSpan> Delivery_Time { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
