//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreweryServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string EmployeeID { get; set; }
        public string Employee_FirstName { get; set; }
        public string Employee_Lastname { get; set; }
        public string Employee_IdentityNumber { get; set; }
        public string Employee_JobRole { get; set; }
        public Nullable<System.DateTime> Employee_Dob { get; set; }
        public Nullable<long> Employee_CellNumber { get; set; }
        public string Employee_Address { get; set; }
        public Nullable<System.DateTime> Employee_DateJoined { get; set; }
        public Nullable<double> Employee_BasicPay { get; set; }
        public Nullable<int> Employee_HoursWorked { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
